### ISSUE TITLE
[BUG] / [ISSUE] Update error

### ISSUE THREAD

**Issue by GKid94** [PierroD/Market#12]
**Describe the bug**
Error when updating market

**To Reproduce**
1. Go to settings
2. Press update

**Expected behavior**
For the program to update to the 2.4.9 version

**Screenshots**
Added

**Additional context**
/
![Screenshot 2024-04-15 005123](https://github.com/PierroD/Market/assets/18757054/1e2f67b8-5cfb-4f35-812a-78f1eb25e9f4)
![Screenshot 2024-04-15 005551](https://github.com/PierroD/Market/assets/18757054/00194e95-749a-4bae-a5c5-f925bf7157a9)

**Comment by GKid94** [comment]
Also showing error when loading a saved profile with FOV changed to 90
![Screenshot 2024-04-20 031929](https://github.com/PierroD/Market/assets/18757054/b375ab00-c925-45b9-a555-181523629eb5)

**Comment by PierroD** [comment]
for the update message, is because the Market is still open while it should be closed, you can run the updater manually.

**Comment by PierroD** [comment]
Can you share your config file ?

**Comment by GKid94** [comment]
> for the update message, is because the Market is still open while it should be closed, you can run the updater manually.

The Market has a update button

**Comment by GKid94** [comment]
> Can you share your config file ?

How?

**Comment by GKid94** [comment]
> Can you share your config file ?

Here
[Fannste.zip](https://github.com/PierroD/Market/files/15138308/Fannste.zip)

**Comment by GKid94** [comment]
IE [INTERNAL ERROR] stefa  27.04.2024 < 15:09:37.5014 >  System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\stefa\Desktop\logs\MarketLogs_27.04.2024.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at PLogger.Log.writeToJson(String filePath, MessageJson msgJson, PLoggerElement target) in D:\Develop\Projets\perso\PLogger\Logger.cs:line 381
   at PLogger.Log.whichMethodToLog() in D:\Develop\Projets\perso\PLogger\Logger.cs:line 263
IE [INTERNAL ERROR] stefa  27.04.2024 < 15:09:37.6301 >  System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\stefa\Desktop\logs\MarketLogs_27.04.2024.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at PLogger.Log.writeToJson(String filePath, MessageJson msgJson, PLoggerElement target) in D:\Develop\Projets\perso\PLogger\Logger.cs:line 381
   at PLogger.Log.whichMethodToLog() in D:\Develop\Projets\perso\PLogger\Logger.cs:line 263
IE [INTERNAL ERROR] stefa  27.04.2024 < 15:09:37.6351 >  System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\stefa\Desktop\logs\MarketLogs_27.04.2024.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at PLogger.Log.writeToJson(String filePath, MessageJson msgJson, PLoggerElement target) in D:\Develop\Projets\perso\PLogger\Logger.cs:line 381
   at PLogger.Log.whichMethodToLog() in D:\Develop\Projets\perso\PLogger\Logger.cs:line 263
IE [INTERNAL ERROR] stefa  27.04.2024 < 15:09:39.0592 >  System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\stefa\Desktop\logs\MarketLogs_27.04.2024.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at PLogger.Log.writeToJson(String filePath, MessageJson msgJson, PLoggerElement target) in D:\Develop\Projets\perso\PLogger\Logger.cs:line 381
   at PLogger.Log.whichMethodToLog() in D:\Develop\Projets\perso\PLogger\Logger.cs:line 263
IE [INTERNAL ERROR] stefa  27.04.2024 < 15:09:39.0622 >  System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\stefa\Desktop\logs\MarketLogs_27.04.2024.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at PLogger.Log.writeToJson(String filePath, MessageJson msgJson, PLoggerElement target) in D:\Develop\Projets\perso\PLogger\Logger.cs:line 381
   at PLogger.Log.whichMethodToLog() in D:\Develop\Projets\perso\PLogger\Logger.cs:line 263
IE [INTERNAL ERROR] stefa  27.04.2024 < 15:09:39.0882 >  System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\stefa\Desktop\logs\MarketLogs_27.04.2024.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at PLogger.Log.writeToJson(String filePath, MessageJson msgJson, PLoggerElement target) in D:\Develop\Projets\perso\PLogger\Logger.cs:line 381
   at PLogger.Log.whichMethodToLog() in D:\Develop\Projets\perso\PLogger\Logger.cs:line 263
IE [INTERNAL ERROR] stefa  27.04.2024 < 15:09:39.2933 >  System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\stefa\Desktop\logs\MarketLogs_27.04.2024.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at PLogger.Log.writeToJson(String filePath, MessageJson msgJson, PLoggerElement target) in D:\Develop\Projets\perso\PLogger\Logger.cs:line 381
   at PLogger.Log.whichMethodToLog() in D:\Develop\Projets\perso\PLogger\Logger.cs:line 263
IE [INTERNAL ERROR] stefa  27.04.2024 < 15:09:39.3543 >  System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\stefa\Desktop\logs\MarketLogs_27.04.2024.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at PLogger.Log.writeToJson(String filePath, MessageJson msgJson, PLoggerElement target) in D:\Develop\Projets\perso\PLogger\Logger.cs:line 381
   at PLogger.Log.whichMethodToLog() in D:\Develop\Projets\perso\PLogger\Logger.cs:line 263

**Comment by GKid94** [comment]
[ExceptionErrorPLogger_08.05.2024.log](https://github.com/PierroD/Market/files/15244860/ExceptionErrorPLogger_08.05.2024.log)
